[build]
	publish = "_site"
	command = "bash scripts/build.sh"

[functions]
	# directory = "netlify/functions"
	node_bundler = "esbuild"

[dev]
	command = "deno task serve"
	targetPort = 3000
	port = 8080
	publish = "_site/"
	autoLaunch = false
	framework = "#custom"

# Package endpoint
[[edge_functions]]
	path = "/x/*"
	function = "pkg"

# API - package completion
[[edge_functions]]
	path = "/api/x/*"
	function = "api-pkg"

[[redirects]]
	from = "/*"
	to = "/404"
	status = 404
